# integrations/notifications.py
# Purpose: Sends triage session summary to the doctor via Gmail.
# Uses Google Gmail API (same credentials as calendar.py) instead
# of SendGrid — simpler since we already have Google OAuth set up.
# Doctor receives a formatted email after every triage session.

import sys
import os
import base64                    # For encoding email content for Gmail API
from email.mime.text import MIMEText  
# MIMEText: builds a properly formatted email message

# Find the absolute path of the directory containing 'integrations'
# This works whether you are in 'src' or 'integrations'
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)

if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from integrations.creds_verification import get_google_services
# Shared Google credential handler

def send_summary(user_profile, diagnosis, risk_tier):
    """
    Sends triage session summary email to the patient's doctor via Gmail.
    Called automatically from pages/03_results.py after every session.

    user_profile: flat dict from db.get_patient_profile()
                  has keys: name, age, allergies, conditions, physician
    diagnosis: dict from llm.run_inference()
    risk_tier: string — "LOW", "MEDIUM", "HIGH", or "UNCERTAIN"
    Returns: True if sent successfully, False if failed
    """
    # ── GET DOCTOR CONTACT DETAILS ────────────────────────────────────
    # physician is a nested dict inside user_profile
    # Structure: {"name": "...", "hospital": "...", "email": "..."}
    physician = user_profile.get("physician", {})
    doctor_email = physician.get("email", "")
    doctor_name = physician.get("name", "Doctor")

    # Cannot send email without a doctor email address
    if not doctor_email:
        print("[notifications] No doctor email found in profile — skipping notification")
        return False

    # ── GET PATIENT DETAILS ───────────────────────────────────────────
    patient_name = user_profile.get("name", "Unknown Patient")
    patient_age = user_profile.get("age", "Unknown")
    patient_allergies = user_profile.get("allergies", "None")
    patient_conditions = user_profile.get("conditions", "None")

    # ── FORMAT TOP CONDITIONS ─────────────────────────────────────────
    # top_conditions is a list of dicts: [{"name": "...", "probability": 75}]
    top_conditions = diagnosis.get("top_conditions", [])
    conditions_text = "\n".join([
        f"  {i+1}. {c.get('name', 'Unknown')} — {c.get('probability', 0)}% probability"
        for i, c in enumerate(top_conditions)
    ])
    if not conditions_text:
        conditions_text = "  No conditions identified"

    # ── FORMAT WARNINGS ───────────────────────────────────────────────
    warnings = diagnosis.get("warnings", [])
    warnings_text = "\n".join([f"  • {w}" for w in warnings])
    if not warnings_text:
        warnings_text = "  None"

    # ── FORMAT REMEDIES ───────────────────────────────────────────────
    remedies = diagnosis.get("remedies", [])
    remedies_text = "\n".join([f"  • {r}" for r in remedies])
    if not remedies_text:
        remedies_text = "  None (not applicable for this risk level)"

    # ── BUILD EMAIL BODY ──────────────────────────────────────────────
    email_body = f"""
Dear Dr. {doctor_name},

An AI-assisted triage session has been completed for your patient.
Please review this summary and follow up as clinically appropriate.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PATIENT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Name              : {patient_name}
Age               : {patient_age}
Known Conditions  : {patient_conditions}
Known Allergies   : {patient_allergies}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TRIAGE RESULTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Risk Level        : {risk_tier}
AI Confidence     : {diagnosis.get('confidence_score', 0):.0%}

TOP CONDITIONS IDENTIFIED:
{conditions_text}

WARNINGS TO MONITOR:
{warnings_text}

HOME CARE SUGGESTIONS (if applicable):
{remedies_text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{diagnosis.get('summary', 'No summary available')}

SOURCES USED:
{', '.join(diagnosis.get('sources', ['Not specified']))}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{diagnosis.get('disclaimer', 'This is not a substitute for clinical judgment.')}

This report was generated by an AI triage assistant and requires 
clinical review by a licensed healthcare professional.
Do not use this report as the sole basis for clinical decisions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Sent by AI Patient Triage App — CareDevi Hackathon 2026
"""

    # ── BUILD EMAIL MESSAGE ───────────────────────────────────────────
    # MIMEText creates a properly formatted plain text email
    mime_message = MIMEText(email_body, "plain")
    mime_message["to"] = doctor_email
    mime_message["subject"] = (
        f"[{risk_tier} RISK] AI Triage Summary — {patient_name}"
    )

    # Gmail API requires the email to be base64 encoded
    # encode_message converts MIMEText to the format Gmail API expects
    encoded_message = base64.urlsafe_b64encode(
        mime_message.as_bytes()
    ).decode()

    # ── SEND VIA GMAIL API ────────────────────────────────────────────
    services = get_google_services()

    if not services:
        print("[notifications] Could not get Google services — email not sent")
        return False

    try:
        # Gmail API send endpoint
        # "me" means send from the authenticated user's Gmail account
        result = services["gmail"].users().messages().send(
            userId="me",
            body={"raw": encoded_message}
        ).execute()

        print(f"[notifications] Email sent successfully!")
        print(f"[notifications] Message ID: {result.get('id')}")
        print(f"[notifications] Sent to: {doctor_email}")
        return True

    except Exception as e:
        print(f"[notifications] Failed to send email: {e}")
        return False


if __name__ == "__main__":
    print("=" * 50)
    print("Testing Gmail Notification")
    print("=" * 50)

    # Mock user profile — matches flat dict from db.get_patient_profile()
    mock_profile = {
        "name": "Test Patient",
        "age": 35,
        "conditions": "Type 2 Diabetes",
        "allergies": "Penicillin",
        "physician": {
            "name": "Smith",
            # Change this to YOUR email to receive the test email
            "email": "your-email@gmail.com",
            "hospital": "City Medical Center"
        }
    }

    # Mock diagnosis — matches output from llm.run_inference()
    mock_diagnosis = {
        "top_conditions": [
            {"name": "Ear Infection", "probability": 75},
            {"name": "Sinusitis", "probability": 20}
        ],
        "confidence_score": 0.75,
        "risk_tier": "medium",
        "warnings": [
            "Watch for fever above 102F",
            "Seek care if hearing loss worsens"
        ],
        "remedies": [],
        "summary": "Symptoms suggest a possible ear infection. A doctor visit is recommended within 24 hours.",
        "sources": ["MedlinePlus", "CDC"],
        "disclaimer": "This is not a substitute for clinical judgment."
    }

    result = send_summary(mock_profile, mock_diagnosis, "MEDIUM")

    if result:
        print("\nTEST PASSED — Check your email inbox!")
    else:
        print("\nTEST FAILED — Check error messages above")

    print("=" * 50)